# ===================================================================
# Spring Boot configuration for the "prod" profile.
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.mycompany.myapp: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myapp
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  liquibase:
    contexts: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: mikestrike555@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  thymeleaf:
    cache: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json,application/javascript,application/xml+atom,application/xml+rss
    min-response-size: 1024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

jhipster:
  security:
    authentication:
      jwt:
        # use a strong base64 encoded secret key
        secret: 3JGGclSZVxPcenr2iYRbCHL4HHIAk3zrBb6kxbxdM6BWm48Fvf0w9ljfzfyBbDe13JUEJaK21rDoXdbu4lUGhg==
  cors:
    allowed-origins: 'http://localhost:8100,http://localhost:9000'
    allowed-methods: GET,PUT,POST,DELETE,OPTIONS
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

  registry:
    password: admin
# ===================================================================
# Additional custom properties
# ===================================================================

# Add any additional custom properties required for production
