# ===================================================================
# Spring Boot configuration for production profile.
# ===================================================================

spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myapp
    password:

  jpa:
    hibernate:
      ddl-auto: validate # Avoid using 'update' in production
    show-sql: false # Turn this off in production for performance and security

  liquibase:
    contexts: prod # Make sure this is set to 'prod' in production
    change-log: classpath:/config/liquibase/changelog/master.xml # Verify the path for production

  mail:
    host: smtp.gmail.com # Your production mail server
    port: 587
    username: mikestrike555@gmail.com
    password: ${MAIL_PASSWORD} # Set this as an environment variable or secret
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com # Your production mail server

  thymeleaf:
    cache: true # Enable template caching in production

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Your production Eureka server
    register-with-eureka: true
    fetch-registry: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,info' # Expose only necessary endpoints

server:
  port: 8080
  servlet:
    context-path: / # Adjust if you use a different context path
    session:
      cookie:
        http-only: true

# ===================================================================
# Security Configuration Adjustments for production.
# ===================================================================
security:
  basic:
    enabled: false # If you are using OAuth2/OIDC, basic security should be disabled
  oauth2:
    client:
      # Configure OAuth2 client details for production

# ===================================================================
# CORS and JHipster-specific Configurations
# ===================================================================
jhipster:
  cors:
    allowed-origins: 'http://localhost:8100,http://localhost:9000'
    allowed-methods: 'GET,POST,PUT,DELETE'
    allowed-headers: 'Authorization,Content-Type'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800

  mail:
    from: mikestrike555@gmail.com # Replace with your production email domain

  security:
    content-security-policy: "default-src 'self'; ... " # Define a strict CSP for production

# ===================================================================
# Application Properties (Add your custom properties here)
# ===================================================================
# application:
# Custom properties for production
