# ===================================================================
# Spring Boot configuration.
# ===================================================================

spring:
  config:
    activate:
      on-profile: '!api-docs'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  liquibase:
    change-log: classpath:/config/liquibase/changelog/master.xml
    parameters:
      search-path: ./src/main/resources/config/liquibase/changelog
  mail:
    host: smtp.gmail.com
    port: 587
    username: mikestrike555@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  application:
    name: myapp

  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs

springdoc:
  show-actuator: true
  api-docs:
    enabled: false

# ===================================================================
# Eureka Client Configuration
# ===================================================================
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    appname: myapp
    instanceId: myapp:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
      context-path: ${server.servlet.context-path:}

# ===================================================================
# Management and Metrics
# ===================================================================
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'jhimetrics',
            'jhiopenapigroups',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump',
            'liquibase',
          ]
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

# ===================================================================
# Server and Servlet Configuration
# ===================================================================
server:
  servlet:
    session:
      cookie:
        http-only: true

# ===================================================================
# Security Configuration Adjustments for Login-less Setup
# ===================================================================
security:
  oauth2:
    client:
      # Assuming you might disable or adjust the security for a login-less experience
      # This section may be adjusted or disabled accordingly

# ===================================================================
# CORS and JHipster-specific Configurations
# ===================================================================
jhipster:
  cors:
    allowed-origins: 'http://localhost:8100,http://localhost:9000'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  mail:
    from: myapp@localhost
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/**
    management-include-pattern: ${server.servlet.context-path:}/management/**
    title: Myapp API
    description: Myapp API documentation
    version: 0.0.1
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:"
# ===================================================================
# Application Properties (Add your custom properties here)
# ===================================================================

# application:
