version: '3.8'

services:
  myapp-app:
    image: myapp:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@localhost:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:${JHIPSTER_REGISTRY_PASSWORD}@localhost:8761/config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/myapp
      - SPRING_DATASOURCE_USERNAME=myapp
      - SPRING_DATASOURCE_PASSWORD=
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'

  myapp-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'

  jhipster-registry:
    image: jhipster/jhipster-registry:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    ports:
      - '8761:8761'

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://localhost:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    ports:
      - '9080:8080'
      - '9443:8443'

networks:
  default:
    external:
      name: myapp-network
