version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command:
      - '-b 0.0.0.0'
      - '-Dkeycloak.profile.feature.upload_scripts=enabled'
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - '-Dkeycloak.migration.file=/opt/keycloak/data/import/realm-export.json'
      - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://localhost:5432/keycloak # Production database host
      - KC_DB_USERNAME=keycloak # Set as an environment variable
      - KC_DB_PASSWORD=keycloak # Set as an environment variable
    ports:
      - '8443:8443' # Expose the ports as required in production
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
